# These are supported GitHub Sponsors and funding platforms for AmniQuest & Amn Ecosystem

github: [alhaq-studio, HabiburRahman]
custom: ['https://alhaq.studio/AmniSpace', 'https://alhaq.studio/donate']
open_collective: alhaq-studio
ko_fi: alhaqstudio
buy_me_a_coffee: alhaqstudio
